server:
  port: 5001

spring:
  application:
    name: order-pay-01
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.233.148:3308/seata_01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.xhx.order


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:6001/eureka/
  instance:
    instance-id: order5001
    prefer-ip-address: true
    # 单位为秒（默认是30秒）
    lease-renewal-interval-in-seconds: 1
    # 单位为秒（默认是90秒）
    lease-expiration-duration-in-seconds: 2


ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。